name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    name: Python Lint, Typecheck & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies (editable + dev extras)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (ruff + black --check)
        run: |
          ruff check .
          black --check .

      - name: Type check (mypy)
        run: |
          mypy backend

      - name: Run tests (pytest)
        env:
          # Ensure tests don't hit external Redis/Compose
          ENV: test
        run: |
          pytest -q

  docker-build:
    name: Docker Compose Build (sanity)
    runs-on: ubuntu-latest
    needs: python-ci
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all services
        run: |
          docker compose version
          docker compose build --no-cache
